"""empty message

Revision ID: 805a95be2644
Revises: cd76ae828d64
Create Date: 2020-03-08 17:39:08.434650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805a95be2644'
down_revision = 'cd76ae828d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'subscribed')
    # ### end Alembic commands ###
