"""empty message

Revision ID: dae97e181ed4
Revises: ee0c1f0b24dd
Create Date: 2020-05-01 18:15:21.251335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae97e181ed4'
down_revision = 'ee0c1f0b24dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread', 'date_created')
    # ### end Alembic commands ###
